import { Item } from "./types/types";
export const objectsData: Record<string, Item> = {
// export const objectsData = {
  rock: {
    title: "Small Rock",
    description: "What's under this rock?",
    color: "silver",
    contains: ["gateKey"],
    canBePickedUp: false,
    room: 'Front Gate',
    x: 80,
    y: 80,
  },
  gateKey: {
    title: "Gold Key",
    description: "A heavy gold key. I wonder what it's for.",
    color: "gold",
    contains: [],
    room: 'Front Gate',
    x: 80,
    y: 80,
  },
  gate: {
    title: "Front Gate",
    description: "The gate is locked.",
    color: "gold",
    contains: [],
    room: 'Front Gate',
    x: 45,
    y: 50,
  },
  address: {
    title: "Address Sign",
    description: "I'll inspect the address sign.",
    color: "purple",
    contains: ["addressScrews"],
    room: 'Front Gate',
    x: 10,
    y: 30,
  },
  addressScrews: {
    title: "Screws",
    description:
      "There seems to be something written on the wall. How can I unscrew this sign?",
    color: "silver",
    contains: ["addressSymbols"],
    room: 'Front Gate',
    x: 10,
    y: 30,
  },
  addressSymbols: {
    title: "DBCA",
    description: "What do these symbols mean?",
    color: "black",
    contains: [],
    room: 'Front Gate',
    x: 10,
    y: 30,
  },
  mailbox: {
    title: "Mailbox",
    description: "What's inside this mailbox?",
    color: "maroon",
    contains: ["letter"],
    room: 'Front Gate',
    x: 70,
    y: 50,
  },
  letter: {
    title: "Letter",
    description: "Someone's favorite plants...",
    color: "magenta",
    contains: [],
    room: 'Front Gate',
    x: 70,
    y: 50,
  },
};
